name: docker build push trivy scanning
on:
  workflow_call:
  push:
  workflow_dispatch:
jobs:
docker_build_push:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:${{ github.run_number }} .
        
trivy_scanning:
    runs-on: ubuntu-latest
    needs: docker_build_push
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
            image-ref: '${{ secrets.DOCKER_REPO }}:${{ github.run_number }}'
            format: 'sarif'
            output: 'trivy-results.sarif'
  
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: 'trivy-results.sarif'
    
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}:${{ github.run_number }}
