name: mail
on:
  workflow_dispatch:
jobs:
 Mail:
    runs-on: ubuntu-latest
    steps:
    - name: Send mail
      if: always()
      env:
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 465
          SMTP_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      run: |
          #echo "Subject: Workflow failed" | sendmail -v -S $SMTP_SERVER -P $SMTP_PORT -xu $SMTP_USERNAME -xp $SMTP_PASSWORD hamrithaanand02@gmail.com
          echo "subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}" > email.txt
          echo -e "From: SMTP_USERNAME\nTo: hamrithaanand02@gmail.com \n" >> email.txt
          echo -e "The status of workflow run.subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }} \n" >> email.txt
          cat email.txt | curl --url "smtps://$SMTP_SERVER:$SMTP_PORT" --ssl-reqd --mail-from "Gokul" --mail-rcpt "hamrithaanand02@gmail.com" --user "$SMTP_USERNAME:$SMTP_PASSWORD" -T -
          cat email.txt | curl --url "smtps://$SMTP_SERVER:$SMTP_PORT" --ssl-reqd --mail-from "Gokul" --mail-rcpt "ponngokul23@gmail.com" --user "$SMTP_USERNAME:$SMTP_PASSWORD" -T -
          cat email.txt | curl --url "smtps://$SMTP_SERVER:$SMTP_PORT" --ssl-reqd --mail-from "Gokul" --mail-rcpt "ashishvpradhan92@gmail.com" --user "$SMTP_USERNAME:$SMTP_PASSWORD" -T -
