name: angular
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        
    - name: Installation
      run: npm install
     
    - name: Build
      run: npm run build
      
    - name: test
      run: npm test
