name: angular
on:
  # push:
  workflow_dispatch:
jobs:
  build_and_test:
      name: build
      uses: ./.github/workflows/npmbuild_and_test.yaml
      secrets: inherit
      
  security_scan:
      name: GGshield
      uses: ./.github/workflows/ggshield.yml
      secrets: inherit
      
  Snyk:
      name: Snyk
      uses: ./.github/workflows/snyk.yml
      secrets: inherit
  
  SBOM:
      name: SBOM
      uses: ./.github/workflows/sbom.yml
      secrets: inherit
 
  Docker_build_push:
      name: docker
      uses: ./.github/workflows/docker.yml
      secrets: inherit
  
  Deployment:
      name: deployment
      uses: ./.github/workflows/deploy.yml
      secrets: inherit
